name: Create Rancher User

on:
  workflow_dispatch:
    inputs:
      rancher_username:
        description: 'Username to create'
        required: true
      rancher_password:
        description: 'Password for new user (min 12 chars)'
        required: true

jobs:
  create-user:
    runs-on: ubuntu-latest
    env:
      RANCHER_API_URL: ${{ secrets.RANCHER_API_URL }}
      RANCHER_API_TOKEN: ${{ secrets.RANCHER_API_TOKEN }}
      RANCHER_USERNAME: ${{ github.event.inputs.rancher_username }}
      RANCHER_PASSWORD: ${{ github.event.inputs.rancher_password }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python & install Ansible + collection
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install ansible
        ansible-galaxy collection install -r requirements.yml

    - name: Run playbook to create Rancher user
      run: |
        source venv/bin/activate
        ansible-playbook create_rancher_user.yml
